services:
  gateway:
    build: ./gateway
    ports:
      - '9088:9088'
    restart: always
    volumes:
      - './gateway/nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
    depends_on:
      - frontend
      - backend
      - chat
    networks:
      network:
        ipv4_address: 67.16.1.7

  mysql:
    image: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - './mysql/dataset:/docker-entrypoint-initdb.d'
      - mysql:/var/lib/mysql
    networks:
      network:
        ipv4_address: 67.16.1.77

  frontend:
    build: ./client
    ports:
      - "7090:8080"
    volumes:
      - './client/nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
    depends_on:
      - backend
      - chat
    networks:
      network:
        ipv4_address: 67.16.1.64

  chat:
    build: ./server
    ports:
      - "4589:3000"
    environment:
      - PORT=3000
    depends_on:
      - backend
    networks:
      network:
        ipv4_address: 67.16.1.45

  backend:
    build: ./api
    ports:
      - "2537:8080"
    environment:
      - PORT=3001
    depends_on:
      - mysql
    networks:
      network:
        ipv4_address: 67.16.1.154

volumes:
  mysql:

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 67.16.0.0/16
          gateway: 67.16.0.1